DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;

CREATE TABLE branchess (
  id SERIAL PRIMARY KEY NOT NULL,
  lat VARCHAR(255) NOT NULL,
  lng VARCHAR(255) NOT NULL
);

CREATE TABLE promotions (
  id SERIAL PRIMARY KEY NOT NULL,
  branch_id INTEGER REFERENCES branches(id) ON DELETE CASCADE,
  capption VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NOT NULL
);