DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;

CREATE TABLE branches (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL

);
CREATE TABLE promotions (
  id SERIAL PRIMARY KEY NOT NULL,
  branch_id INTEGER REFERENCES branches(id) ON DELETE CASCADE,
);