DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;

CREATE TABLE branchess (
  id SERIAL PRIMARY KEY NOT NULL,
  lat NUMERIC NOT NULL,
  lng NUMERIC NOT NULL
);
CREATE TABLE promotions (
  id SERIAL PRIMARY KEY NOT NULL,
  branch_id INTEGER REFERENCES branches(id) ON DELETE CASCADE,
  caption VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NOT NULL
);